version: 2.24.5

services:
  website:
    image: 'node:21-bookworm-slim'
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npm ci && npm run start"