version: 2.24.5

services:
  api:
    image: "golang:1.22.0-bookworm"
    ports:
      - "3000:3000"
    networks:
      - client-side
      - server-side
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go build . && ./api"